import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/lib/Navbar";
import Footer from "@/lib/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata = {
  title: 'Learnova — Learn. Build. Grow.',
  description: 'Enterprise-grade Learning Management System with backend role-based access control.',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
   <body className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
